-- +migrate Up

ALTER TABLE `user` ADD COLUMN intro VARCHAR(500) NOT NULL DEFAULT '' COMMENT '自我介绍';
ALTER TABLE `user` ADD COLUMN country_code VARCHAR(10) NOT NULL DEFAULT '' COMMENT '国籍/地区ISO代码';
ALTER TABLE `user` ADD COLUMN country VARCHAR(80) NOT NULL DEFAULT '' COMMENT '国籍/地区显示名';
ALTER TABLE `user` ADD COLUMN native_languages VARCHAR(500) NOT NULL DEFAULT '' COMMENT '母语JSON数组，最多5个';
ALTER TABLE `user` ADD COLUMN learning_languages VARCHAR(500) NOT NULL DEFAULT '' COMMENT '学习语言JSON数组，最多5个';
ALTER TABLE `user` ADD COLUMN birthday VARCHAR(20) NOT NULL DEFAULT '' COMMENT '出生日期 yyyy-MM-dd';
