FROM debian:bookworm-slim

ARG TARGETARCH
WORKDIR /home

ENV TZ=Asia/Shanghai

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY assets /home/assets
COPY configs /home/configs
COPY --chmod=0755 linux_${TARGETARCH} /home/app

ENTRYPOINT ["/home/app"]
